# Create the docker secret
# kubectl create secret generic doubtingben-docker-hub-regcred --from-file=.dockerconfigjson=/home/bwilson/.docker/config.json  --type=kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: doubtingben-docker-hub
secrets:
  - name: doubtingben-docker-hub-regcred
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: doubtingben-tekton
secrets:
  - name: doubtingben-docker-hub-regcred  