---
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  generateName: zagent-build-docker-
spec:
  serviceAccountName: zagent-service
  taskRef:
    name: build-image-and-push
  inputs:
    resources:
      - name: docker-source
        resourceRef:
          name: git-doubtingben-zagent
    params:
      - name: pathToDockerFile
        value: /workspace/docker-source/Dockerfile
      - name: pathToContext
        # Point to Dockerfile
        value: /workspace/docker-source/
  outputs:
    resources:
      - name: builtImage
        resourceRef:
          name: image-dockerhub-zagent