---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: cloudlog-pr-pipeline-template
spec:
  params:
    - name: gitHubProject
      description: Github project name
    - name: gitRepositoryURL
      description: Git repo url
    - name: gitCommit
      description: Git commit to build from
      default: master
    - name: short_sha
      description: Short sha from git commit used to identify binaries
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: cloudlog-pr-pipeline-
      spec:
        serviceAccountName: ecc-tekton
        pipelineRef:
          name: cloudlog-pr-pipeline
        resources:
          - name: source
            resourceSpec:
              type: git
              params:
                - name: revision
                  value: $(params.gitCommit)
                - name: url
                  value: $(params.gitRepositoryURL)
        params:
          - name: shortSha
            value: $(params.short_sha)
          - name: gitRepositoryURL
            value: $(params.gitRepositoryURL)
          - name: gitCommit
            value: $(params.gitCommit)
          - name: gitHubProject
            value: $(params.gitHubProject)              