apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: listener-interceptor
spec:
  serviceAccountName: tekton-triggers-admin
  serviceType: LoadBalancer
  triggers:
## Test trigger for chat interaction through comments
    - name: chatbot-trig
      interceptors:
        - github:
            secretRef:
              secretName: listener-interceptor-github-shared-secret
              secretKey: token
            eventTypes:
              - pull_request
              - issue_comment
      bindings:
        - name: chatbot-binding
      template:
        name: chatbot-template
## zagent master push events
    - name: zagent-master-trigger
      interceptors:
        - github:
            secretRef:
              secretName: listener-interceptor-github-shared-secret
              secretKey: token
            eventTypes:
              - push
        - cel:
            filter: >-
              body.ref == 'refs/heads/master'
              && body.repository.full_name == 'doubtingben/zagent'
      bindings:
        - name: docker-build-binding-zagent
      template:
        name: docker-build-template
## zagent pull_request events
    - name: zagent-pr-trigger
      interceptors:
        - github:
            secretRef:
              secretName: listener-interceptor-github-shared-secret
              secretKey: token
            eventTypes:
              - pull_request
        - cel:
            filter: >-
              body.repository.full_name == 'doubtingben/zagent'
              && ( body.pull_request.author_association == 'OWNER'
                   ||
                   body.pull_request.author_association == 'COLLABORATOR'
              && ( body.action == 'opened' || body.action == 'synchronize')
            overlays:
              - key: short_sha
                expression: 'truncate(body.pull_request.head.sha, 7)'
      bindings:
        - name: zagent-pr-binding
      template:
        name: zagent-pr-pipeline-template