---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: zagent-pr-pipeline
spec:
  resources:
    - name: source
      type: git
  params:
    - name: shortSha
    - name: gitHubProject
    - name: gitCommit
  tasks:
    - name: set-status-pending
      taskRef:
        name: github-set-status
      params:
        - name: REPO_FULL_NAME
          value: $(params.gitHubProject)
        - name: SHA
          value: $(params.gitCommit)
        - name: TARGET_URL
          value: http://google.com
        - name: DESCRIPTION
          value: Attempting to build a binary
        - name: CONTEXT
          value: build-binary/check
        - name: STATE
          value: pending
    - name: zagent-binary-build
      runAfter:
        - set-status-pending
      taskRef:
        name: zagent-binary-build
      params:
        - name: shortSha
          value: $(params.shortSha)
      resources:
        inputs:
          - name: source
            resource: source
    - name: set-status-success
      runAfter:
        - zagent-binary-build
      taskRef:
        name: github-set-status
      params:
        - name: REPO_FULL_NAME
          value: $(params.gitHubProject)  
        - name: SHA
          value: $(params.gitCommit)  
        - name: TARGET_URL
          value: http://google.com
        - name: DESCRIPTION
          value: Sucessfully built a binary
        - name: CONTEXT
          value: build-binary/check
        - name: STATE
          value: success