---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: zagent-pr-template
spec:
  params:
    - name: gitRepositoryURL
      description: Git repo url
    - name: gitCommit
      description: Git commit to build from
      default: master
    - name: short_sha
      description: Short sha from git commit used to identify binaries
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: TaskRun
      metadata:
        generateName: zagent-binary-build-
      spec:
        taskRef:
          name: zagent-binary-build
        resources:
          inputs:
            - name: source
              resourceSpec:
                type: git
                params:
                  - name: revision
                    value: $(params.gitCommit)
                  - name: url
                    value: $(params.gitRepositoryURL)
        params:
          - name: shortSha
            value: $(params.short_sha)
  